---

name: "Linting"

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"

      - name: "Install uv"
        run: |
          pip install uv
          uv sync

      - name: "Run ruff formatting"
        run: "uv run ruff format --check ."

      - name: "Run ruff linting"
        run: "uv run ruff check ."

      - name: "Run mypy"
        run: "uv run mypy ."
