---

name: "Linting"

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          enable-cache: true

      - name: "Run ruff formatting"
        run: "uv run ruff format --check ."

      - name: "Run ruff linting"
        run: "uv run ruff check ."

      - name: "Run mypy"
        run: "uv run mypy ."
